### ISSUE TITLE
icp ceres扰动相关

### ISSUE THREAD

**Issue by SpriteLin-ZJU** [chengwei0427/testICP#1]
你好，
icp ceres代码中扰动求导时你用的是
dp_by_se3.block<3, 3>(0, 0) = -skew(q_last_curr * cur_pt);
但floam用的是
dp_by_se3.block<3, 3>(0, 0) = -skew(lp);

我自己测试了下好像下面那种写法的解是正确的，上面的写法会无法收敛。
想请教下是否哪里有问题

**Comment by chengwei0427** [comment]
你好@SpriteLin-ZJU  
感谢关注！
这里需要注意左乘和右乘时，加号的更新方式存在差异；

**Comment by SpriteLin-ZJU** [comment]
> 你好@SpriteLin-ZJU 感谢关注！ 这里需要注意左乘和右乘时，加号的更新方式存在差异；

**Comment by SpriteLin-ZJU** [comment]
两种写法都是左扰动？SE3上的话不应该是下面的写法么

**Comment by chengwei0427** [comment]
都是左扰动的，不过我是so3和t上分别求导的

**Comment by chengwei0427** [comment]
> 



> 你好， icp ceres代码中扰动求导时你用的是 dp_by_se3.block<3, 3>(0, 0) = -skew(q_last_curr * cur_pt); 但floam用的是 dp_by_se3.block<3, 3>(0, 0) = -skew(lp);
> 
> 我自己测试了下好像下面那种写法的解是正确的，上面的写法会无法收敛。 想请教下是否哪里有问题

我测试过，会正常收敛的啊；你看下+操作那里是否正确。
