### ISSUE TITLE
请问左扰动和右扰动的坐标系有区别吗

### ISSUE THREAD

**Issue by w8128835** [chengwei0427/testICP#2]
您好，在位姿计算的时候，左乘姿态矩阵是基于世界坐标系的变换，右乘姿态矩阵是基于body系的变换，由于对这个不怎么懂，想请教您一下：
a.求导时的左扰动和右扰动有这种区别吗?
b.如果a不是坐标系定义的区别，为什么会有左扰动和右扰动的区分，它们分别用于什么情况呢？

打扰您了

**Comment by chengwei0427** [comment]
1. 左右扰动，是有一定区别的；
2. 这个问题，我不知道怎么解答啊，你可以问问相关的大佬们！抱歉

**Comment by w8128835** [comment]
> 

好的，非常感谢
